[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.11.6"
tokio = "1.13.0"
serde = "1.0.130"
sdk = { path = "../sdk" }
error = { path = "../error" }
types = { path = "../types" }
